# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ihakwalkExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ihakwalkExample
  pod 'iHAKWalk', :path => '../'

  target 'ihakwalkExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
